version: '3.8'
services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: 'pesa-core'
    environment:
      - 'POSTGRES_DB=pesacoredb'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432'